Repository EvgeniyaYakunina/zoo-market, pull requests merged in 2025-02, with the labels that each got.

#16 feature: add PreviewCard component
  src/content/PreviewCard/PreviewCard.tsx
  src/content/PreviewCard/index.ts
  src/content/index.ts
  src/pages/Footer/index.tsx
  src/pages/_app.tsx
  src/pages/card/index.tsx
  src/pages/index.tsx
  src/styles/palette.ts
  tailwind.config.ts
Labels: feature, refactor

#17 Feature/zm 14
  package.json
  pnpm-lock.yaml
  src/assets/CheckmarkOutline.tsx
  src/assets/index.ts
  src/components/Card/Card.tsx
  src/components/Header/Header.tsx
  src/components/layout/layout.tsx
  src/components/ui/checkbox/checkbox.tsx
  src/components/ui/checkbox/index.ts
  src/components/ui/index.ts
  src/components/ui/tabs/index.ts
  src/components/ui/tabs/tabs.tsx
  src/content/Main/Main.tsx
  src/content/Main/index.ts
  src/content/PreviewCard/PreviewCard.tsx
  src/content/Shop/Shop.tsx
  src/content/Shop/index.ts
  src/content/index.ts
  src/pages/api/hello.ts
  src/pages/index.tsx
Labels: feature

#22 Feature/zm 20
  README.md
  package.json
  pnpm-lock.yaml
  src/app/api/api.ts
  src/app/api/api.types.ts
  src/app/api/index.ts
  src/app/store.ts
  src/utils/apiEndpoints.ts
  src/utils/index.ts
Labels: feature

#23 Feature/zm 15
  src/components/Basket/Basket.tsx
  src/components/Basket/BasketList.tsx
  src/components/Basket/index.ts
  src/components/Card/Card.tsx
  src/components/Header/Header.tsx
  src/components/Header/SignUpAndBasket/SignUpAndBasket.tsx
  src/components/index.ts
  src/content/Main/Main.tsx
  src/pages/basket/index.tsx
Labels: feature

#24 refactoring: fix imports
  src/components/Basket/Basket.tsx
Labels: refactor

#28 feature:add useGetAllNodeTypesQuery to menu on Main Page
  src/content/Main/Main.tsx
  src/pages/_app.tsx
Labels: feature

#30 feature:add hook useGetAllFiltersQuery for filters in Sidebar
  src/content/Main/Main.tsx
Labels: feature

#33 Feature/zm 27
  src/app/api/api.types.ts
  src/app/store/slices/cardsSlice.ts
  src/app/store/store.ts
  src/components/Card/Card.tsx
  src/components/Header/Header.tsx
  src/content/Main/Main.tsx
  src/pages/_app.tsx
  src/pages/index.tsx
  src/utils/apiEndpoints.ts
Labels: feature

#35 Feature/zm 32
  src/app/store/index.ts
  src/app/store/slices/index.ts
  src/app/store/slices/searchSlice.ts
  src/app/store/store.ts
  src/components/Basket/BasketList.tsx
  src/components/Card/Card.tsx
  src/components/Header/Header.tsx
  src/components/Header/Search/Search.tsx
  src/components/Header/SignUpAndBasket/SignUpAndBasket.tsx
  src/components/ui/tabs/tabs.tsx
  src/content/Main/Main.tsx
  src/hooks/index.ts
  src/hooks/useDebounce.ts
  src/pages/index.tsx
  src/utils/constants.ts
  src/utils/index.ts
Labels: feature

#36 Feature/zm 31
  next.config.ts
  src/components/Card/Card.tsx
  src/content/PreviewCard/PreviewCard.tsx
  src/hooks/index.ts
  src/hooks/useCart.ts
  src/pages/card/[id].tsx
Labels: feature

#37 Feature/zm 34
  package.json
  pnpm-lock.yaml
  src/app/api/api.types.ts
  src/components/Header/SignUpAndBasket/SignUpAndBasket.tsx
  src/components/index.ts
  src/components/ui/index.ts
  src/components/ui/loader/Loader.tsx
  src/components/ui/loader/index.ts
  src/content/Basket/Basket.tsx
  src/content/Basket/BasketList.tsx
  src/content/Basket/index.ts
  src/content/Main/Main.tsx
  src/content/PreviewCard/PreviewCard.tsx
  src/hooks/index.ts
  src/hooks/useErrorHandler.ts
  src/pages/_app.tsx
  src/pages/index.tsx
  src/styles/loader.css
  src/utils/constants.ts
Labels: feature
